apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "react-express-mysql.backendConfigMapName" . }}
  namespace: {{ include "react-express-mysql.namespace" . }}
  labels:
    {{- include "react-express-mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  DATABASE_DB: {{ .Values.backend.env.database | quote }}
  DATABASE_USER: {{ .Values.backend.env.databaseUser | quote }}
  DATABASE_HOST: {{ .Values.backend.env.databaseHost | quote }}
  NODE_ENV: {{ .Values.backend.env.nodeEnv | quote }}

