{{- if not .Values.mysql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "react-express-mysql.mysqlSecretName" . }}
  namespace: {{ include "react-express-mysql.namespace" . }}
  labels:
    {{- include "react-express-mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
data:
  {{ .Values.mysql.auth.secretKey }}: {{ required "mysql.auth.rootPassword is required when mysql.auth.existingSecret is empty" .Values.mysql.auth.rootPassword | b64enc | quote }}
{{- end }}

